name: 'Stale issues'
on:
  schedule:
    - cron: '32 * * * *'

permissions:
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 15
          stale-issue-label: 'stale'
          stale-issue-message: >
                      This issue has been automatically marked as stale because it has not had
                      recent activity. It will be closed if no further activity occurs. Thank you
                      for your contributions.

          debug-only: 'true'
          remove-issue-stale-when-updated: 'true'
          # debug-only: 'true'